# Generated by Django 3.2.5 on 2022-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_process', '0003_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='ball',
            field=models.FloatField(),
        ),
    ]
