# Generated by Django 4.0.3 on 2022-05-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_process', '0004_alter_testresult_ball'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedModule',
        ),
    ]
