# Generated by Django 4.0.3 on 2022-06-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_process', '0006_alter_completedcourses_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolutions',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='tasksolutions',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отметить отклоненным'),
        ),
    ]
