# Generated by Django 3.2.5 on 2022-01-05 03:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('stop_lesson', models.BooleanField(default=False)),
                ('tab_index', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')], max_length=2)),
                ('link', models.TextField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('stop_lesson', models.BooleanField(default=False)),
                ('tab_index', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')], max_length=2)),
                ('time', models.TimeField(default=datetime.time(10, 0))),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('stop_lesson', models.BooleanField(default=False)),
                ('tab_index', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')], max_length=2)),
                ('text', models.TextField()),
                ('response_is_file', models.BooleanField(default=False)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('text', models.TextField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.test')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('stop_lesson', models.BooleanField(default=False)),
                ('tab_index', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('ts', 'test'), ('lc', 'lecture'), ('vd', 'video'), ('tk', 'task')], max_length=2)),
                ('text', models.TextField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
