# Generated by Django 3.2.5 on 2022-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20220111_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tab_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='tab_index',
            field=models.IntegerField(default=0),
        ),
    ]
