# Generated by Django 3.2.5 on 2022-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20220111_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolecture',
            name='link',
        ),
        migrations.AddField(
            model_name='videolecture',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
