# Generated by Django 3.2.5 on 2022-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20220313_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
