# Generated by Django 3.2.5 on 2022-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_videolecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
