# Generated by Django 3.2.5 on 2022-03-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_videolecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_draft',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
