# Generated by Django 4.0.3 on 2022-05-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20220318_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='min_ball',
            field=models.FloatField(default=60.0),
        ),
    ]
