# Generated by Django 4.0.3 on 2022-05-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_test_min_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='min_ball',
            field=models.IntegerField(default=60),
        ),
    ]
