# Generated by Django 4.0.3 on 2022-06-02 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_test_min_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='min_ball',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
