# Generated by Django 4.0.3 on 2022-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, upload_to='course_photo'),
        ),
    ]
